Make the output/input fail when processor fails
openconfig/gnmic pull request #285
Opened 2023-11-10 10:05 UTC by netixx

In the case where the event processor fails to initialise (could be for example a bad processor config, file not found, starlark syntax error), the previous behaviour was to ignore the processor.

However an event-processor can be crucial to the event processing and ignoring it could lead to garbage in the downstream metrics platform. It could lead for example to cardinality explosion.

This changes makes the input or output component fail if any processor in the chain fails to initilise.

2023-11-11 19:32 UTC, karimra requested changes
Maybe it would make sense to merge both `MakeEventProcessors` for inputs and outputs into a single function and put it under the `formatters` package ?
I know the inputs one does not include `actions` config for now. It can be left `nil` for inputs.

2023-11-11 22:42 UTC, karimra approved these changes

2023-11-11 22:42 UTC, merged

2023-11-11 22:43 UTC, karimra commented
Ended up making the changes myself, thanks for the contribution!

2023-11-14 08:10 UTC, netixx commented
Oh sorry I just saw you message right now!

thanks :)